////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3053
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=2.0.50727.1432.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class distInfo {
    
//    private book[] bookField;
    
//    private file[] fileSetField;
    
//    private string versionField;
    
//    public distInfo() {
//        this.versionField = "2005-1";
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("book")]
//    public book[] book {
//        get {
//            return this.bookField;
//        }
//        set {
//            this.bookField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
//    public file[] fileSet {
//        get {
//            return this.fileSetField;
//        }
//        set {
//            this.fileSetField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string version {
//        get {
//            return this.versionField;
//        }
//        set {
//            this.versionField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class book {
    
//    private docTitle docTitleField;
    
//    private docAuthor[] docAuthorField;
    
//    private smilRef[] distMapField;
    
//    private changeMsg[] changeMsgField;
    
//    private string uidField;
    
//    private string pkgRefField;
    
//    private string mediaField;
    
//    /// <remarks/>
//    public docTitle docTitle {
//        get {
//            return this.docTitleField;
//        }
//        set {
//            this.docTitleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("docAuthor")]
//    public docAuthor[] docAuthor {
//        get {
//            return this.docAuthorField;
//        }
//        set {
//            this.docAuthorField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("smilRef", IsNullable=false)]
//    public smilRef[] distMap {
//        get {
//            return this.distMapField;
//        }
//        set {
//            this.distMapField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("changeMsg")]
//    public changeMsg[] changeMsg {
//        get {
//            return this.changeMsgField;
//        }
//        set {
//            this.changeMsgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string uid {
//        get {
//            return this.uidField;
//        }
//        set {
//            this.uidField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string pkgRef {
//        get {
//            return this.pkgRefField;
//        }
//        set {
//            this.pkgRefField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string media {
//        get {
//            return this.mediaField;
//        }
//        set {
//            this.mediaField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class docTitle {
    
//    private string textField;
    
//    private audio audioField;
    
//    private img imgField;
    
//    private string langField;
    
//    /// <remarks/>
//    public string text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    public audio audio {
//        get {
//            return this.audioField;
//        }
//        set {
//            this.audioField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class audio {
    
//    private string srcField;
    
//    private string clipBeginField;
    
//    private string clipEndField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipBegin {
//        get {
//            return this.clipBeginField;
//        }
//        set {
//            this.clipBeginField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipEnd {
//        get {
//            return this.clipEndField;
//        }
//        set {
//            this.clipEndField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class img {
    
//    private string srcField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class docAuthor {
    
//    private string textField;
    
//    private audio audioField;
    
//    private img imgField;
    
//    private string langField;
    
//    /// <remarks/>
//    public string text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    public audio audio {
//        get {
//            return this.audioField;
//        }
//        set {
//            this.audioField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class smilRef {
    
//    private string fileField;
    
//    private string mediaRefField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string file {
//        get {
//            return this.fileField;
//        }
//        set {
//            this.fileField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string mediaRef {
//        get {
//            return this.mediaRefField;
//        }
//        set {
//            this.mediaRefField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class changeMsg {
    
//    private object[] itemsField;
    
//    private string mediaRefField;
    
//    private string langField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string mediaRef {
//        get {
//            return this.mediaRefField;
//        }
//        set {
//            this.mediaRefField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class file {
    
//    private string fileRefField;
    
//    private string mediaRefField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string fileRef {
//        get {
//            return this.fileRefField;
//        }
//        set {
//            this.fileRefField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string mediaRef {
//        get {
//            return this.mediaRefField;
//        }
//        set {
//            this.mediaRefField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class distMap {
    
//    private smilRef[] smilRefField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("smilRef")]
//    public smilRef[] smilRef {
//        get {
//            return this.smilRefField;
//        }
//        set {
//            this.smilRefField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/distInfo-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/distInfo-2005-1", IsNullable=false)]
//public partial class fileSet {
    
//    private file[] fileField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("file")]
//    public file[] file {
//        get {
//            return this.fileField;
//        }
//        set {
//            this.fileField = value;
//        }
//    }
//}
