////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3053
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=2.0.50727.1432.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class smil {
    
//    private head headField;
    
//    private body bodyField;
    
//    private string idField;
    
//    private string classField;
    
//    private string titleField;
    
//    private string langField;
    
//    /// <remarks/>
//    public head head {
//        get {
//            return this.headField;
//        }
//        set {
//            this.headField = value;
//        }
//    }
    
//    /// <remarks/>
//    public body body {
//        get {
//            return this.bodyField;
//        }
//        set {
//            this.bodyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class head {
    
//    private meta[] metaField;
    
//    private layout layoutField;
    
//    private meta[] meta1Field;
    
//    private customAttributes customAttributesField;
    
//    private meta[] meta2Field;
    
//    private string idField;
    
//    private string classField;
    
//    private string titleField;
    
//    private string langField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("meta", Order=0)]
//    public meta[] meta {
//        get {
//            return this.metaField;
//        }
//        set {
//            this.metaField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
//    public layout layout {
//        get {
//            return this.layoutField;
//        }
//        set {
//            this.layoutField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("meta", Order=2)]
//    public meta[] meta1 {
//        get {
//            return this.meta1Field;
//        }
//        set {
//            this.meta1Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
//    public customAttributes customAttributes {
//        get {
//            return this.customAttributesField;
//        }
//        set {
//            this.customAttributesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("meta", Order=4)]
//    public meta[] meta2 {
//        get {
//            return this.meta2Field;
//        }
//        set {
//            this.meta2Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class meta {
    
//    private string nameField;
    
//    private string contentField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class layout {
    
//    private region[] regionField;
    
//    private string idField;
    
//    private string classField;
    
//    private string titleField;
    
//    private string langField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("region")]
//    public region[] region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class region {
    
//    private string idField;
    
//    private string heightField;
    
//    private string widthField;
    
//    private string bottomField;
    
//    private string topField;
    
//    private string leftField;
    
//    private string rightField;
    
//    private regionFit fitField;
    
//    private string zindexField;
    
//    private string backgroundColorField;
    
//    private regionShowBackground showBackgroundField;
    
//    public region() {
//        this.heightField = "auto";
//        this.widthField = "auto";
//        this.bottomField = "auto";
//        this.topField = "auto";
//        this.leftField = "auto";
//        this.rightField = "auto";
//        this.fitField = regionFit.hidden;
//        this.showBackgroundField = regionShowBackground.always;
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute("auto")]
//    public string height {
//        get {
//            return this.heightField;
//        }
//        set {
//            this.heightField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute("auto")]
//    public string width {
//        get {
//            return this.widthField;
//        }
//        set {
//            this.widthField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute("auto")]
//    public string bottom {
//        get {
//            return this.bottomField;
//        }
//        set {
//            this.bottomField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute("auto")]
//    public string top {
//        get {
//            return this.topField;
//        }
//        set {
//            this.topField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute("auto")]
//    public string left {
//        get {
//            return this.leftField;
//        }
//        set {
//            this.leftField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute("auto")]
//    public string right {
//        get {
//            return this.rightField;
//        }
//        set {
//            this.rightField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(regionFit.hidden)]
//    public regionFit fit {
//        get {
//            return this.fitField;
//        }
//        set {
//            this.fitField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute("z-index")]
//    public string zindex {
//        get {
//            return this.zindexField;
//        }
//        set {
//            this.zindexField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string backgroundColor {
//        get {
//            return this.backgroundColorField;
//        }
//        set {
//            this.backgroundColorField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(regionShowBackground.always)]
//    public regionShowBackground showBackground {
//        get {
//            return this.showBackgroundField;
//        }
//        set {
//            this.showBackgroundField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//public enum regionFit {
    
//    /// <remarks/>
//    hidden,
    
//    /// <remarks/>
//    fill,
    
//    /// <remarks/>
//    meet,
    
//    /// <remarks/>
//    scroll,
    
//    /// <remarks/>
//    slice,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//public enum regionShowBackground {
    
//    /// <remarks/>
//    always,
    
//    /// <remarks/>
//    whenActive,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class customAttributes {
    
//    private customTest[] customTestField;
    
//    private string idField;
    
//    private string classField;
    
//    private string titleField;
    
//    private string langField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("customTest")]
//    public customTest[] customTest {
//        get {
//            return this.customTestField;
//        }
//        set {
//            this.customTestField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class customTest {
    
//    private string idField;
    
//    private string classField;
    
//    private customTestDefaultState defaultStateField;
    
//    private string titleField;
    
//    private string langField;
    
//    private customTestOverride overrideField;
    
//    public customTest() {
//        this.defaultStateField = customTestDefaultState.@false;
//        this.overrideField = customTestOverride.hidden;
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(customTestDefaultState.@false)]
//    public customTestDefaultState defaultState {
//        get {
//            return this.defaultStateField;
//        }
//        set {
//            this.defaultStateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(customTestOverride.hidden)]
//    public customTestOverride @override {
//        get {
//            return this.overrideField;
//        }
//        set {
//            this.overrideField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//public enum customTestDefaultState {
    
//    /// <remarks/>
//    @true,
    
//    /// <remarks/>
//    @false,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//public enum customTestOverride {
    
//    /// <remarks/>
//    visible,
    
//    /// <remarks/>
//    hidden,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class body {
    
//    private object[] itemsField;
    
//    private string idField;
    
//    private string classField;
    
//    private string titleField;
    
//    private string langField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("a", typeof(a))]
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("img", typeof(img))]
//    [System.Xml.Serialization.XmlElementAttribute("par", typeof(par))]
//    [System.Xml.Serialization.XmlElementAttribute("seq", typeof(seq))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class a {
    
//    private object[] itemsField;
    
//    private string idField;
    
//    private string classField;
    
//    private string titleField;
    
//    private string langField;
    
//    private string hrefField;
    
//    private aExternal externalField;
    
//    public a() {
//        this.externalField = aExternal.@false;
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("img", typeof(img))]
//    [System.Xml.Serialization.XmlElementAttribute("par", typeof(par))]
//    [System.Xml.Serialization.XmlElementAttribute("seq", typeof(seq))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string title {
//        get {
//            return this.titleField;
//        }
//        set {
//            this.titleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string href {
//        get {
//            return this.hrefField;
//        }
//        set {
//            this.hrefField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(aExternal.@false)]
//    public aExternal external {
//        get {
//            return this.externalField;
//        }
//        set {
//            this.externalField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class audio {
    
//    private string idField;
    
//    private string srcField;
    
//    private string clipBeginField;
    
//    private string clipEndField;
    
//    private string regionField;
    
//    private string typeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipBegin {
//        get {
//            return this.clipBeginField;
//        }
//        set {
//            this.clipBeginField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipEnd {
//        get {
//            return this.clipEndField;
//        }
//        set {
//            this.clipEndField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class img {
    
//    private string idField;
    
//    private string regionField;
    
//    private string srcField;
    
//    private string typeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class par {
    
//    private object[] itemsField;
    
//    private string idField;
    
//    private string classField;
    
//    private string customTestField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("a", typeof(a))]
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("img", typeof(img))]
//    [System.Xml.Serialization.XmlElementAttribute("seq", typeof(seq))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
//    public string customTest {
//        get {
//            return this.customTestField;
//        }
//        set {
//            this.customTestField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class seq {
    
//    private object[] itemsField;
    
//    private string idField;
    
//    private string classField;
    
//    private string customTestField;
    
//    private string durField;
    
//    private string endField;
    
//    private seqFill fillField;
    
//    public seq() {
//        this.fillField = seqFill.remove;
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("a", typeof(a))]
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("img", typeof(img))]
//    [System.Xml.Serialization.XmlElementAttribute("par", typeof(par))]
//    [System.Xml.Serialization.XmlElementAttribute("seq", typeof(seq))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
//    public string customTest {
//        get {
//            return this.customTestField;
//        }
//        set {
//            this.customTestField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string dur {
//        get {
//            return this.durField;
//        }
//        set {
//            this.durField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string end {
//        get {
//            return this.endField;
//        }
//        set {
//            this.endField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(seqFill.remove)]
//    public seqFill fill {
//        get {
//            return this.fillField;
//        }
//        set {
//            this.fillField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/dtbsmil-2005-2", IsNullable=false)]
//public partial class text {
    
//    private string idField;
    
//    private string regionField;
    
//    private string srcField;
    
//    private string typeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string region {
//        get {
//            return this.regionField;
//        }
//        set {
//            this.regionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
//public enum seqFill {
    
//    /// <remarks/>
//    freeze,
    
//    /// <remarks/>
//    remove,
//}

/////// <remarks/>
////[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
////[System.SerializableAttribute()]
////[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/dtbsmil-2005-2")]
////public enum aExternal {
    
////    /// <remarks/>
////    @true,
    
////    /// <remarks/>
////    @false,
////}
