////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3053
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=2.0.50727.1432.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class ncx {
    
//    private object[] headField;
    
//    private docTitle docTitleField;
    
//    private docAuthor[] docAuthorField;
    
//    private navMap navMapField;
    
//    private pageList pageListField;
    
//    private navList[] navListField;
    
//    private string versionField;
    
//    private string langField;
    
//    private ncxDir dirField;
    
//    private bool dirFieldSpecified;
    
//    public ncx() {
//        this.versionField = "2005-1";
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("meta", typeof(meta), IsNullable=false)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("smilCustomTest", typeof(smilCustomTest), IsNullable=false)]
//    public object[] head {
//        get {
//            return this.headField;
//        }
//        set {
//            this.headField = value;
//        }
//    }
    
//    /// <remarks/>
//    public docTitle docTitle {
//        get {
//            return this.docTitleField;
//        }
//        set {
//            this.docTitleField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("docAuthor")]
//    public docAuthor[] docAuthor {
//        get {
//            return this.docAuthorField;
//        }
//        set {
//            this.docAuthorField = value;
//        }
//    }
    
//    /// <remarks/>
//    public navMap navMap {
//        get {
//            return this.navMapField;
//        }
//        set {
//            this.navMapField = value;
//        }
//    }
    
//    /// <remarks/>
//    public pageList pageList {
//        get {
//            return this.pageListField;
//        }
//        set {
//            this.pageListField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navList")]
//    public navList[] navList {
//        get {
//            return this.navListField;
//        }
//        set {
//            this.navListField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string version {
//        get {
//            return this.versionField;
//        }
//        set {
//            this.versionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public ncxDir dir {
//        get {
//            return this.dirField;
//        }
//        set {
//            this.dirField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool dirSpecified {
//        get {
//            return this.dirFieldSpecified;
//        }
//        set {
//            this.dirFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class meta {
    
//    private string nameField;
    
//    private string contentField;
    
//    private string schemeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string scheme {
//        get {
//            return this.schemeField;
//        }
//        set {
//            this.schemeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class smilCustomTest {
    
//    private string idField;
    
//    private smilCustomTestDefaultState defaultStateField;
    
//    private smilCustomTestOverride overrideField;
    
//    private smilCustomTestBookStruct bookStructField;
    
//    private bool bookStructFieldSpecified;
    
//    public smilCustomTest() {
//        this.defaultStateField = smilCustomTestDefaultState.@false;
//        this.overrideField = smilCustomTestOverride.hidden;
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(smilCustomTestDefaultState.@false)]
//    public smilCustomTestDefaultState defaultState {
//        get {
//            return this.defaultStateField;
//        }
//        set {
//            this.defaultStateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    [System.ComponentModel.DefaultValueAttribute(smilCustomTestOverride.hidden)]
//    public smilCustomTestOverride @override {
//        get {
//            return this.overrideField;
//        }
//        set {
//            this.overrideField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public smilCustomTestBookStruct bookStruct {
//        get {
//            return this.bookStructField;
//        }
//        set {
//            this.bookStructField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool bookStructSpecified {
//        get {
//            return this.bookStructFieldSpecified;
//        }
//        set {
//            this.bookStructFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum smilCustomTestDefaultState {
    
//    /// <remarks/>
//    @true,
    
//    /// <remarks/>
//    @false,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum smilCustomTestOverride {
    
//    /// <remarks/>
//    visible,
    
//    /// <remarks/>
//    hidden,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum smilCustomTestBookStruct {
    
//    /// <remarks/>
//    PAGE_NUMBER,
    
//    /// <remarks/>
//    NOTE,
    
//    /// <remarks/>
//    NOTE_REFERENCE,
    
//    /// <remarks/>
//    ANNOTATION,
    
//    /// <remarks/>
//    LINE_NUMBER,
    
//    /// <remarks/>
//    OPTIONAL_SIDEBAR,
    
//    /// <remarks/>
//    OPTIONAL_PRODUCER_NOTE,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class docTitle {
    
//    private text textField;
    
//    private audio audioField;
    
//    private img imgField;
    
//    private string idField;
    
//    private string langField;
    
//    private docTitleDir dirField;
    
//    private bool dirFieldSpecified;
    
//    /// <remarks/>
//    public text text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    public audio audio {
//        get {
//            return this.audioField;
//        }
//        set {
//            this.audioField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public docTitleDir dir {
//        get {
//            return this.dirField;
//        }
//        set {
//            this.dirField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool dirSpecified {
//        get {
//            return this.dirFieldSpecified;
//        }
//        set {
//            this.dirFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class text {
    
//    private string idField;
    
//    private string classField;
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class audio {
    
//    private string idField;
    
//    private string classField;
    
//    private string srcField;
    
//    private string clipBeginField;
    
//    private string clipEndField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipBegin {
//        get {
//            return this.clipBeginField;
//        }
//        set {
//            this.clipBeginField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipEnd {
//        get {
//            return this.clipEndField;
//        }
//        set {
//            this.clipEndField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class img {
    
//    private string idField;
    
//    private string classField;
    
//    private string srcField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum docTitleDir {
    
//    /// <remarks/>
//    ltr,
    
//    /// <remarks/>
//    rtl,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class docAuthor {
    
//    private text textField;
    
//    private audio audioField;
    
//    private img imgField;
    
//    private string idField;
    
//    private string langField;
    
//    private docAuthorDir dirField;
    
//    private bool dirFieldSpecified;
    
//    /// <remarks/>
//    public text text {
//        get {
//            return this.textField;
//        }
//        set {
//            this.textField = value;
//        }
//    }
    
//    /// <remarks/>
//    public audio audio {
//        get {
//            return this.audioField;
//        }
//        set {
//            this.audioField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public docAuthorDir dir {
//        get {
//            return this.dirField;
//        }
//        set {
//            this.dirField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool dirSpecified {
//        get {
//            return this.dirFieldSpecified;
//        }
//        set {
//            this.dirFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum docAuthorDir {
    
//    /// <remarks/>
//    ltr,
    
//    /// <remarks/>
//    rtl,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class navMap {
    
//    private navInfo[] navInfoField;
    
//    private navLabel[] navLabelField;
    
//    private navPoint[] navPointField;
    
//    private string idField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navInfo")]
//    public navInfo[] navInfo {
//        get {
//            return this.navInfoField;
//        }
//        set {
//            this.navInfoField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navLabel")]
//    public navLabel[] navLabel {
//        get {
//            return this.navLabelField;
//        }
//        set {
//            this.navLabelField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navPoint")]
//    public navPoint[] navPoint {
//        get {
//            return this.navPointField;
//        }
//        set {
//            this.navPointField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class navInfo {
    
//    private object[] itemsField;
    
//    private img imgField;
    
//    private string langField;
    
//    private navInfoDir dirField;
    
//    private bool dirFieldSpecified;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public navInfoDir dir {
//        get {
//            return this.dirField;
//        }
//        set {
//            this.dirField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool dirSpecified {
//        get {
//            return this.dirFieldSpecified;
//        }
//        set {
//            this.dirFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum navInfoDir {
    
//    /// <remarks/>
//    ltr,
    
//    /// <remarks/>
//    rtl,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class navLabel {
    
//    private object[] itemsField;
    
//    private img imgField;
    
//    private string langField;
    
//    private navLabelDir dirField;
    
//    private bool dirFieldSpecified;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public navLabelDir dir {
//        get {
//            return this.dirField;
//        }
//        set {
//            this.dirField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool dirSpecified {
//        get {
//            return this.dirFieldSpecified;
//        }
//        set {
//            this.dirFieldSpecified = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum navLabelDir {
    
//    /// <remarks/>
//    ltr,
    
//    /// <remarks/>
//    rtl,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class navPoint {
    
//    private navLabel[] navLabelField;
    
//    private content contentField;
    
//    private navPoint[] navPoint1Field;
    
//    private string idField;
    
//    private string classField;
    
//    private string playOrderField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navLabel")]
//    public navLabel[] navLabel {
//        get {
//            return this.navLabelField;
//        }
//        set {
//            this.navLabelField = value;
//        }
//    }
    
//    /// <remarks/>
//    public content content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navPoint")]
//    public navPoint[] navPoint1 {
//        get {
//            return this.navPoint1Field;
//        }
//        set {
//            this.navPoint1Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string playOrder {
//        get {
//            return this.playOrderField;
//        }
//        set {
//            this.playOrderField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class content {
    
//    private string idField;
    
//    private string srcField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class pageList {
    
//    private navInfo[] navInfoField;
    
//    private navLabel[] navLabelField;
    
//    private pageTarget[] pageTargetField;
    
//    private string idField;
    
//    private string classField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navInfo")]
//    public navInfo[] navInfo {
//        get {
//            return this.navInfoField;
//        }
//        set {
//            this.navInfoField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navLabel")]
//    public navLabel[] navLabel {
//        get {
//            return this.navLabelField;
//        }
//        set {
//            this.navLabelField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("pageTarget")]
//    public pageTarget[] pageTarget {
//        get {
//            return this.pageTargetField;
//        }
//        set {
//            this.pageTargetField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class pageTarget {
    
//    private navLabel[] navLabelField;
    
//    private content contentField;
    
//    private string idField;
    
//    private string valueField;
    
//    private pageTargetType typeField;
    
//    private string classField;
    
//    private string playOrderField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navLabel")]
//    public navLabel[] navLabel {
//        get {
//            return this.navLabelField;
//        }
//        set {
//            this.navLabelField = value;
//        }
//    }
    
//    /// <remarks/>
//    public content content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public pageTargetType type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string playOrder {
//        get {
//            return this.playOrderField;
//        }
//        set {
//            this.playOrderField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum pageTargetType {
    
//    /// <remarks/>
//    front,
    
//    /// <remarks/>
//    normal,
    
//    /// <remarks/>
//    special,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class navList {
    
//    private navInfo[] navInfoField;
    
//    private navLabel[] navLabelField;
    
//    private navTarget[] navTargetField;
    
//    private string idField;
    
//    private string classField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navInfo")]
//    public navInfo[] navInfo {
//        get {
//            return this.navInfoField;
//        }
//        set {
//            this.navInfoField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navLabel")]
//    public navLabel[] navLabel {
//        get {
//            return this.navLabelField;
//        }
//        set {
//            this.navLabelField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navTarget")]
//    public navTarget[] navTarget {
//        get {
//            return this.navTargetField;
//        }
//        set {
//            this.navTargetField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class navTarget {
    
//    private navLabel[] navLabelField;
    
//    private content contentField;
    
//    private string idField;
    
//    private string classField;
    
//    private string valueField;
    
//    private string playOrderField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("navLabel")]
//    public navLabel[] navLabel {
//        get {
//            return this.navLabelField;
//        }
//        set {
//            this.navLabelField = value;
//        }
//    }
    
//    /// <remarks/>
//    public content content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string @class {
//        get {
//            return this.classField;
//        }
//        set {
//            this.classField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string playOrder {
//        get {
//            return this.playOrderField;
//        }
//        set {
//            this.playOrderField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//public enum ncxDir {
    
//    /// <remarks/>
//    ltr,
    
//    /// <remarks/>
//    rtl,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ncx-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ncx-2005-1", IsNullable=false)]
//public partial class head {
    
//    private object[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("meta", typeof(meta))]
//    [System.Xml.Serialization.XmlElementAttribute("smilCustomTest", typeof(smilCustomTest))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}
