////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:2.0.50727.3053
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// This source code was auto-generated by xsd, Version=2.0.50727.1432.
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class resources {
    
//    private meta[] headField;
    
//    private scope[] scopeField;
    
//    private string versionField;
    
//    private string idField;
    
//    public resources() {
//        this.versionField = "2005-1";
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("meta", IsNullable=false)]
//    public meta[] head {
//        get {
//            return this.headField;
//        }
//        set {
//            this.headField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("scope")]
//    public scope[] scope {
//        get {
//            return this.scopeField;
//        }
//        set {
//            this.scopeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string version {
//        get {
//            return this.versionField;
//        }
//        set {
//            this.versionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class meta {
    
//    private string nameField;
    
//    private string contentField;
    
//    private string schemeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string scheme {
//        get {
//            return this.schemeField;
//        }
//        set {
//            this.schemeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class scope {
    
//    private nodeSet[] nodeSetField;
    
//    private string nsuriField;
    
//    private string idField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("nodeSet")]
//    public nodeSet[] nodeSet {
//        get {
//            return this.nodeSetField;
//        }
//        set {
//            this.nodeSetField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string nsuri {
//        get {
//            return this.nsuriField;
//        }
//        set {
//            this.nsuriField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class nodeSet {
    
//    private resource[] resourceField;
    
//    private string selectField;
    
//    private string idField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("resource")]
//    public resource[] resource {
//        get {
//            return this.resourceField;
//        }
//        set {
//            this.resourceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string select {
//        get {
//            return this.selectField;
//        }
//        set {
//            this.selectField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class resource {
    
//    private object[] itemsField;
    
//    private img imgField;
    
//    private string langField;
    
//    private string idField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("audio", typeof(audio))]
//    [System.Xml.Serialization.XmlElementAttribute("text", typeof(text))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
    
//    /// <remarks/>
//    public img img {
//        get {
//            return this.imgField;
//        }
//        set {
//            this.imgField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
//    public string lang {
//        get {
//            return this.langField;
//        }
//        set {
//            this.langField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class audio {
    
//    private string srcField;
    
//    private string clipBeginField;
    
//    private string clipEndField;
    
//    private string idField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipBegin {
//        get {
//            return this.clipBeginField;
//        }
//        set {
//            this.clipBeginField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string clipEnd {
//        get {
//            return this.clipEndField;
//        }
//        set {
//            this.clipEndField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class text {
    
//    private string idField;
    
//    private textDir dirField;
    
//    private bool dirFieldSpecified;
    
//    private string valueField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public textDir dir {
//        get {
//            return this.dirField;
//        }
//        set {
//            this.dirField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlIgnoreAttribute()]
//    public bool dirSpecified {
//        get {
//            return this.dirFieldSpecified;
//        }
//        set {
//            this.dirFieldSpecified = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlTextAttribute()]
//    public string Value {
//        get {
//            return this.valueField;
//        }
//        set {
//            this.valueField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//public enum textDir {
    
//    /// <remarks/>
//    ltr,
    
//    /// <remarks/>
//    rtl,
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class img {
    
//    private string srcField;
    
//    private string idField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string src {
//        get {
//            return this.srcField;
//        }
//        set {
//            this.srcField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
//    public string id {
//        get {
//            return this.idField;
//        }
//        set {
//            this.idField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/resource-2005-1")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/resource-2005-1", IsNullable=false)]
//public partial class head {
    
//    private meta[] metaField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("meta")]
//    public meta[] meta {
//        get {
//            return this.metaField;
//        }
//        set {
//            this.metaField = value;
//        }
//    }
//}
