//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buttercup.Control.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Speech {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Speech() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buttercup.Control.Resources.Speech", typeof(Speech).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Information.
        /// </summary>
        public static string BookInfoMessage {
            get {
                return ResourceManager.GetString("BookInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book {0} has been loaded..
        /// </summary>
        public static string BookLoaded {
            get {
                return ResourceManager.GetString("BookLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksMessage {
            get {
                return ResourceManager.GetString("BookmarksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings Panel.
        /// </summary>
        public static string DisplaySettingsPanelMessage {
            get {
                return ResourceManager.GetString("DisplaySettingsPanelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Panel.
        /// </summary>
        public static string FindPanelMessage {
            get {
                return ResourceManager.GetString("FindPanelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Panel.
        /// </summary>
        public static string HelpPanelMessage {
            get {
                return ResourceManager.GetString("HelpPanelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change size slider. Current size is at {0} percent.
        /// </summary>
        public static string InterfaceSizeSliderMessage {
            get {
                return ResourceManager.GetString("InterfaceSizeSliderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current size is at {0} percent.
        /// </summary>
        public static string InterfaceSizeSliderPercentage {
            get {
                return ResourceManager.GetString("InterfaceSizeSliderPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Panel.
        /// </summary>
        public static string NavigationPanelMessage {
            get {
                return ResourceManager.GetString("NavigationPanelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot go to page {0}, this book only has {1} pages.
        /// </summary>
        public static string PageNumberInvalidMessage {
            get {
                return ResourceManager.GetString("PageNumberInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Page Text Box.
        /// </summary>
        public static string PageNumTextBoxMessage {
            get {
                return ResourceManager.GetString("PageNumTextBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel Closed..
        /// </summary>
        public static string PanelClosedMessage {
            get {
                return ResourceManager.GetString("PanelClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results found..
        /// </summary>
        public static string ResultsFoundMessage {
            get {
                return ResourceManager.GetString("ResultsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text Box.
        /// </summary>
        public static string SearchTextBoxMessage {
            get {
                return ResourceManager.GetString("SearchTextBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Of Contents.
        /// </summary>
        public static string TableOfContentsMessage {
            get {
                return ResourceManager.GetString("TableOfContentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents: {0}.
        /// </summary>
        public static string TextBoxContentsMessage {
            get {
                return ResourceManager.GetString("TextBoxContentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume slider. Volume is at {0} percent.
        /// </summary>
        public static string VolumeSliderMessage {
            get {
                return ResourceManager.GetString("VolumeSliderMessage", resourceCulture);
            }
        }
    }
}
