//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buttercup.Control.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buttercup.Control.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark Button.
        /// </summary>
        public static string AutomationHelp_AddBookmark {
            get {
                return ResourceManager.GetString("AutomationHelp_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Information Button.
        /// </summary>
        public static string AutomationHelp_BookInfo {
            get {
                return ResourceManager.GetString("AutomationHelp_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings Button.
        /// </summary>
        public static string AutomationHelp_DisplaySettings {
            get {
                return ResourceManager.GetString("AutomationHelp_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Button.
        /// </summary>
        public static string AutomationHelp_Find {
            get {
                return ResourceManager.GetString("AutomationHelp_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Panel Button.
        /// </summary>
        public static string AutomationHelp_HidePanel {
            get {
                return ResourceManager.GetString("AutomationHelp_HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Storage Button.
        /// </summary>
        public static string AutomationHelp_IncreaseIS {
            get {
                return ResourceManager.GetString("AutomationHelp_IncreaseIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Button.
        /// </summary>
        public static string AutomationHelp_Navigation {
            get {
                return ResourceManager.GetString("AutomationHelp_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Section Button.
        /// </summary>
        public static string AutomationHelp_NextSection {
            get {
                return ResourceManager.GetString("AutomationHelp_NextSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Sentence Button.
        /// </summary>
        public static string AutomationHelp_NextSentence {
            get {
                return ResourceManager.GetString("AutomationHelp_NextSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Book Button.
        /// </summary>
        public static string AutomationHelp_OpenBook {
            get {
                return ResourceManager.GetString("AutomationHelp_OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback of the current book.
        /// </summary>
        public static string AutomationHelp_Pause {
            get {
                return ResourceManager.GetString("AutomationHelp_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playback of the current book.
        /// </summary>
        public static string AutomationHelp_Play {
            get {
                return ResourceManager.GetString("AutomationHelp_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Section Button.
        /// </summary>
        public static string AutomationHelp_PreviousSection {
            get {
                return ResourceManager.GetString("AutomationHelp_PreviousSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Sentence Button.
        /// </summary>
        public static string AutomationHelp_PreviousSentence {
            get {
                return ResourceManager.GetString("AutomationHelp_PreviousSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VolumeSlider.
        /// </summary>
        public static string AutomationHelp_VolumeSlider {
            get {
                return ResourceManager.GetString("AutomationHelp_VolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        public static string AutomationName_AddBookmark {
            get {
                return ResourceManager.GetString("AutomationName_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Information.
        /// </summary>
        public static string AutomationName_BookInfo {
            get {
                return ResourceManager.GetString("AutomationName_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        public static string AutomationName_DisplaySettings {
            get {
                return ResourceManager.GetString("AutomationName_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string AutomationName_Find {
            get {
                return ResourceManager.GetString("AutomationName_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Panel.
        /// </summary>
        public static string AutomationName_HidePanel {
            get {
                return ResourceManager.GetString("AutomationName_HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Storage.
        /// </summary>
        public static string AutomationName_IncreaseIS {
            get {
                return ResourceManager.GetString("AutomationName_IncreaseIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string AutomationName_Navigation {
            get {
                return ResourceManager.GetString("AutomationName_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Section.
        /// </summary>
        public static string AutomationName_NextSection {
            get {
                return ResourceManager.GetString("AutomationName_NextSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Sentence.
        /// </summary>
        public static string AutomationName_NextSentence {
            get {
                return ResourceManager.GetString("AutomationName_NextSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Book.
        /// </summary>
        public static string AutomationName_OpenBook {
            get {
                return ResourceManager.GetString("AutomationName_OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Book.
        /// </summary>
        public static string AutomationName_Pause {
            get {
                return ResourceManager.GetString("AutomationName_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Book.
        /// </summary>
        public static string AutomationName_Play {
            get {
                return ResourceManager.GetString("AutomationName_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Section.
        /// </summary>
        public static string AutomationName_PreviousSection {
            get {
                return ResourceManager.GetString("AutomationName_PreviousSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Sentence.
        /// </summary>
        public static string AutomationName_PreviousSentence {
            get {
                return ResourceManager.GetString("AutomationName_PreviousSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string AutomationName_VolumeSlider {
            get {
                return ResourceManager.GetString("AutomationName_VolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (*.zip)|*.zip.
        /// </summary>
        public static string FileOpenDialogFilter {
            get {
                return ResourceManager.GetString("FileOpenDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultListItem.
        /// </summary>
        public static string ListItemStyleKey {
            get {
                return ResourceManager.GetString("ListItemStyleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No book loaded].
        /// </summary>
        public static string NoBook_TitleMessage {
            get {
                return ResourceManager.GetString("NoBook_TitleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        public static string ToolTip_AddBookmark {
            get {
                return ResourceManager.GetString("ToolTip_AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Book Information Panel.
        /// </summary>
        public static string ToolTip_BookInfo {
            get {
                return ResourceManager.GetString("ToolTip_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Display Settings Panel.
        /// </summary>
        public static string ToolTip_DisplaySettings {
            get {
                return ResourceManager.GetString("ToolTip_DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Find Panel.
        /// </summary>
        public static string ToolTip_Find {
            get {
                return ResourceManager.GetString("ToolTip_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Panel.
        /// </summary>
        public static string ToolTip_HidePanel {
            get {
                return ResourceManager.GetString("ToolTip_HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Isolated Storage.
        /// </summary>
        public static string ToolTip_IncreaseIS {
            get {
                return ResourceManager.GetString("ToolTip_IncreaseIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Navigation Panel.
        /// </summary>
        public static string ToolTip_Navigation {
            get {
                return ResourceManager.GetString("ToolTip_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Section.
        /// </summary>
        public static string ToolTip_NextSection {
            get {
                return ResourceManager.GetString("ToolTip_NextSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Sentence.
        /// </summary>
        public static string ToolTip_NextSentence {
            get {
                return ResourceManager.GetString("ToolTip_NextSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Book.
        /// </summary>
        public static string ToolTip_OpenBook {
            get {
                return ResourceManager.GetString("ToolTip_OpenBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Book.
        /// </summary>
        public static string ToolTip_Pause {
            get {
                return ResourceManager.GetString("ToolTip_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Book.
        /// </summary>
        public static string ToolTip_Play {
            get {
                return ResourceManager.GetString("ToolTip_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Section.
        /// </summary>
        public static string ToolTip_PreviousSection {
            get {
                return ResourceManager.GetString("ToolTip_PreviousSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Sentence.
        /// </summary>
        public static string ToolTip_PreviousSentence {
            get {
                return ResourceManager.GetString("ToolTip_PreviousSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string ToolTip_VolumeSlider {
            get {
                return ResourceManager.GetString("ToolTip_VolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Buttercup!.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
